# Generated by Django 2.1 on 2018-10-12 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=2, unique=True)),
                ('type', models.CharField(choices=[('s', 'sensor'), ('r', 'relay')], max_length=1)),
                ('lastTime', models.TimeField(default='12:35')),
                ('pin', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
            ],
            options={
                'verbose_name_plural': 'Devices',
            },
        ),
    ]
