# Generated by Django 2.1 on 2018-08-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.CharField(max_length=100)),
                ('ipaddress', models.CharField(max_length=20)),
                ('port', models.CharField(default='80', max_length=10)),
                ('publickey', models.CharField(max_length=1000)),
            ],
        ),
    ]
